"""empty message

Revision ID: ea84e7a02b20
Revises: 9b0891d63f2a
Create Date: 2025-04-22 20:53:23.929599

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea84e7a02b20"
down_revision: str | None = "9b0891d63f2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("game", "active_user_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("game", "choice_user_id", existing_type=sa.BIGINT(), nullable=True)
    op.add_column("question", sa.Column("theme_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(
        op.f("fk_question_theme_id_theme"), "question", "theme", ["theme_id"], ["id"]
    )
    op.add_column(
        "question_to_theme", sa.Column("round_id", sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_question_to_theme_round_id_round"),
        "question_to_theme",
        "round",
        ["round_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_question_to_theme_round_id_round"),
        "question_to_theme",
        type_="foreignkey",
    )
    op.drop_column("question_to_theme", "round_id")
    op.drop_constraint(
        op.f("fk_question_theme_id_theme"), "question", type_="foreignkey"
    )
    op.drop_column("question", "theme_id")
    op.alter_column("game", "choice_user_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("game", "active_user_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
